version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
