version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}

  caddy:
    image: caddy2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

networks:
  app-network:
    driver: bridge
