services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    ports:
      - "8080:8080"

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

      # This is required for certificated to be stored. ~/caddy/<app_name> is the directory
      # for each application. We don't want to lose the certificates when we redeploy.
      - ~/caddy/app:/data

networks:
  app-network:
    driver: bridge
