- name: Local SSH key verification and creation
  hosts: localhost
  gather_facts: no
  vars:
    ssh_key_private: "{{ lookup('env','HOME') + '/.ssh/id_ed25519' }}"
    ssh_key_public: "{{ lookup('env','HOME') + '/.ssh/id_ed25519.pub' }}"

  tasks:
    - name: Check if ed25519 SSH key exists locally
      ansible.builtin.stat:
        path: "{{ ssh_key_public }}"
        follow: yes
      register: ssh_key

    - name: Inform if SSH key does not exist
      ansible.builtin.debug:
        msg: "No ed25519 SSH key found, consider creating one."
      when: not ssh_key.stat.exists

    - name: Prompt to create SSH key if not present
      pause:
        prompt: "No ed25519 SSH key found. Do you want to create one? (yes/no)"
      register: user_input
      when: not ssh_key.stat.exists

    - name: Generate ed25519 SSH key
      ansible.builtin.command:
        cmd: "ssh-keygen -t ed25519 -f {{ ssh_key_private }} -N ''"
      when: user_input.user_input | lower == 'yes'

- name: Transfer local SSH key to remote hosts
  hosts: all
  become: true
  vars:
    username: ubuntu
    ssh_key_public: "{{ lookup('env','HOME') + '/.ssh/id_ed25519.pub' }}"

  tasks:
    - name: Ensure .ssh directory exists on remote
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'

    - name: Add local SSH key to remote user
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', ssh_key_public) }}"
        exclusive: no
