---
- name: Deploy a "hello world" Caddy server with Docker
  hosts: all
  become: yes

  tasks:
    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create Caddy configuration directory
      file:
        path: "{{ ansible_env.PWD }}/caddy"
        state: directory
        mode: "0755"

    - name: Remove existing Caddyfile if it exists
      file:
        path: "{{ ansible_env.PWD }}/caddy/Caddyfile"
        state: absent
      ignore_errors: yes

    - name: Create Caddyfile
      copy:
        dest: "{{ ansible_env.PWD }}/caddy/Caddyfile"
        content: |
          foo.z.rednafi.com {
            respond "Hello, World!"
          }
        mode: "0644"
        force: yes

    - name: Pull Caddy image
      docker_image:
        name: caddy
        source: pull

    - name: Run Caddy container
      docker_container:
        name: caddy
        image: caddy:latest
        state: started
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - "{{ ansible_env.PWD }}/caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
        restart_policy: always
