name: Test, build, and deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Check go fmt
        run: cd app && gofmt -l . | tee fmt.log && test -z "$(cat fmt.log)"

      - name: Run tests
        working-directory: ./app
        run: |
          go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Install kamal
        run: gem install kamal

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:omni

      - name: Check Tailscale status
        run: sudo tailscale status

      - name: Test Tailscale ping to target machine
        run: sudo tailscale ping hetzner-ubuntu

      - name: Test SSH connection (verbose)
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@hetzner-ubuntu 'echo "SSH into Tailscale network successful"'

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - name: Bring down Tailscale
        run: sudo tailscale down
