name: Test, build, and deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Check go fmt
        run: cd app && gofmt -l . | tee fmt.log && test -z "$(cat fmt.log)"

      - name: Run tests
        working-directory: ./app
        run: |
          go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Cache kamal
        uses: actions/cache@v4
        with:
          path: /usr/local/bundle
          key: kamal-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            kamal-${{ runner.os }}-

      - name: Install kamal (only if cache misses)
        if: steps.cache.outputs.cache-hit != 'true'
        run: gem install kamal

      - name: Cache Tailscale binaries
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/tailscale
          key: tailscale-${{ runner.os }}-${{ hashFiles('**/install.sh') }}
          restore-keys: |
            tailscale-${{ runner.os }}-

      - name: Install Tailscale (only if cache misses)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Set up Tailscale
        run: |
          sudo tailscale up \
            --authkey "${{ secrets.TAILSCALE_AUTH_TOKEN }}" \
            --ssh \
            --advertise-tags="tag:omni"
          sleep 10
        env:
          TAILSCALE_AUTH_TOKEN: ${{ secrets.TAILSCALE_AUTH_TOKEN }}

      - name: Check Tailscale status
        run: sudo tailscale status

      - name: Test Tailscale ping to target machine
        run: sudo tailscale ping hetzner-ubuntu

      - name: Test SSH connection (verbose)
        run: |
          ssh -v -o StrictHostKeyChecking=no root@hetzner-ubuntu 'echo "SSH into Tailscale network successful"'
