name: Test, build, and deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Check go fmt
        run: cd app && gofmt -l . | tee fmt.log && test -z "$(cat fmt.log)"

      - name: Run tests
        working-directory: ./app
        run: |
          go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Install kamal
        run: gem install kamal

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection (verbose)
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@116.203.21.146 'echo "SSH into server successful"'

      - name: Create .env for kamal (this is a hack!)
        run: |
          echo "KAMAL_REGISTRY_PASSWORD=${{ secrets.KAMAL_REGISTRY_PASSWORD }}" > .env
          echo "APP_AUTH_TOKEN=${{ secrets.APP_AUTH_TOKEN }}" >> .env

      - name: Deploy to VM with Kamal
        run: |
          set -o allexport; source .env; set +o allexport; kamal deploy -vvv

      # Always clean up the .env file, even if deployment fails
      - name: Clean up .env file
        if: always()
        run: |
          rm -f .env
