name: Test, build, and deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Check go fmt
        run: cd app && gofmt -l . | tee fmt.log && test -z "$(cat fmt.log)"

      - name: Run tests
        run: |
          cd app
          go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to github container registry
        env:
          GH_USER: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: docker login ghcr.io -u $GH_USER -p $GH_TOKEN

      - name: Build docker images
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: docker compose -f app/docker-compose.yml build

      - name: Tag and push docker images
        env:
          APP_IMAGE_NAME: ghcr.io/${{ github.repository }}/app:latest
          CADDY_IMAGE_NAME: ghcr.io/${{ github.repository }}/caddy:latest
        run: |
          docker tag app-app:latest $APP_IMAGE_NAME
          docker tag app-caddy:latest $CADDY_IMAGE_NAME
          docker push $APP_IMAGE_NAME
          docker push $CADDY_IMAGE_NAME

      - name: Install ssh keys in the ci
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts

      - name: Connect to remote machine, pull, and start the service
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          WORK_DIR: ${{ secrets.WORK_DIR }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_SERVER_URL: ${{ github.server_url }}
          GH_REPO: ${{ github.repository}}
          APP_AUTH_TOKEN: ${{ secrets.APP_AUTH_TOKEN }}
        run: |
          SCRIPT="
            set -e

            # Start by removing existing work directory in the remote server
            rm -rf $WORK_DIR

            # Clone the repo in the remote server
            git clone https://$GH_TOKEN@github.com/$GH_REPO.git $WORK_DIR

            # Go to the directory where the docker-compose.yml lives
            cd $WORK_DIR/app

            # Wind everything down and clean up all the containers associated with this file
            docker compose down --rmi all --volumes --remove-orphans || true

            # Sometimes images don't go away
            docker rmi -f $(docker compose images -q) || true

            # Export environment variables
            export AUTH_TOKEN=$

            # Spin up the containers with the environment variable from the .env file
            docker compose up -d --build
          "

          # Run on the remote machine
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "$SCRIPT"

      - name: Remove ssh directory
        run: rm -rf ~/.ssh
